version: '2.1'

volumes:
    grafana_data: {}

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_DEFAULT_THEME=light
      - GF_EXPLORE_ENABLED=true
      - GF_ALERTING_ENABLED=false
      - GF_UNIFIED_ALERTING_ENABLED=true
      - GF_FEATURE_TOGGLES_ENABLE=traceToMetrics,publicDashboards,tempoApmTable
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - qryn
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "5"

  qryn:
    image: qxip/qryn:latest
    container_name: qryn
    restart: unless-stopped
    expose:
      - 3100
    ports:
      - "3100:3100"
    environment:
      - CLICKHOUSE_SERVER=YOURHOST.clickhouse.cloud
      - CLICKHOUSE_PROTO=https
      - CLICKHOUSE_PORT=8443
      - CLICKHOUSE_AUTH=default:YOURPASSWORD
      - NODE_OPTIONS="--max-old-space-size=4096"
      - ALERTMAN_URL=http://alertman:9093
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "5"

  fluxpipe:
    image: ghcr.io/metrico/fluxpipe:latest
    container_name: fluxpipe
    restart: unless-stopped
    expose:
      - 8086
    ports:
      - "8086:8086"
    depends_on:
      - qryn
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "5"

  vector:
    image: timberio/vector:latest-alpine
    container_name: vector
    restart: unless-stopped
    volumes:
      - ./vector/vector.toml:/etc/vector/vector.toml:ro
    depends_on:
      - qryn
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "5"

  exporter:
    build: ./dummy-exporter
    container_name: exporter
    restart: unless-stopped
    ports:
      - "9090:8080"
    depends_on:
      - qryn
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "5"

  dummy-server:
    build: ./dummy-server
    container_name: dummy-server
    restart: unless-stopped
    ports:
      - 4000:4000
      - 80:80
    depends_on:
      - qryn
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "5"

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    hostname: mailhog
    expose:
      - 1025
      - 8025
    ports:
      - "8025:8025"
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "5"
      
  alertman:
    image: prom/alertmanager:latest
    container_name: alertman
    hostname: alertman
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    expose:
      - 9093
    ports:
      - 9093:9093
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "5"
