# config file version
apiVersion: 1

deleteDatasources:
  - name: Loki
    orgId: 1
  - name: Tempo
    orgId: 1
  - name: Prometheus
    orgId: 1
  - name: Flux
    orgId: 1
  - name: Pyroscope
    orgId: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    uid: loki
    url: http://qryn:3100
    editable: true
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "^.*?traceI[d|D]=(\\w+).*$"
          name: traceId
          url: '$${__value.raw}'
        - datasourceUid: tempo
          matcherRegex: "^.*?\"traceID\":\"(\\w+)\".*$"
          name: traceID
          url: '$${__value.raw}'
  - name: Tempo
    type: tempo
    access: proxy
    uid: tempo
    url: http://qryn:3100
    editable: true
    jsonData:
      nodeGraph:
        enabled: true
      tracesToLogs:
        datasourceUid: loki
        filterByTraceID: false
        spanEndTimeShift: "2000ms"
        spanStartTimeShift: "-2000ms"
        tags: ['job']
      tracesToMetrics:
        datasourceUid: prometheus
        tags: ['job']
      serviceMap:
        datasourceUid: prometheus
      lokiSearch:
        datasourceUid: loki
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: prometheus
    url: http://qryn:3100
    editable: true
    basicAuth: false
    jsonData:
      httpMethod: GET
      graphiteVersion: "1.1"
      tlsAuth: false
      tlsAuthWithCACert: false
      cacheLevel: 'High'
      incrementalQuerying: 'Enable'
      incrementalQueryOverlapWindow: 2m
  - name: Flux
    type: influxdb
    uid: flux
    version: 2
    access: proxy
    url: http://fluxpipe:8086
    basicAuth: false
    jsonData:
      defaultBucket:
      httpMode: POST
      organization: qryn
      version: Flux
    secureJsonData:
      token:
  - id: 1
    name: grafana-pyroscope-datasource
    type: grafana-pyroscope-datasource
    typeLogoUrl: public/app/plugins/datasource/grafana-pyroscope-datasource/img/grafana_pyroscope_icon.svg
    access: proxy
    url: http://qryn:3100
    user: ""
    database: ""
    basicAuth: false
    basicAuthUser: ""
    withCredentials: false
    isDefault: true
    jsonData: { }
    secureJsonFields: { }
    version: 2
    readOnly: false
    accessControl:
      alert.instances.external:read: true
      alert.instances.external:write: true
      alert.notifications.external:read: true
      alert.notifications.external:write: true
      alert.rules.external:read: true
      alert.rules.external:write: true
      datasources.id:read: true
      datasources:delete: true
      datasources:query: true
      datasources:read: true
      datasources:write: true
    apiVersion: ""
    # secureJsonData:
    #   apiKey: {YOUR_API_KEY}
